[package]
name = "aakash_scanner"
description="simple tool for detecting 阿三 in Chinese telegram groups"
version = "0.1.0"
authors = ["duangsuse <fedora-opensuse@outlook.com>"]

[dependencies]
rusqlite = "0.12.0"
telegram-bot = "0.5.0"
regex = "0.2.2"
